apiVersion: `build.openshift.io/v1`
kind: BuildConfig
metadata:
  name: stunnel
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'stunnel:latest'
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/jonnynch/stunnel-openshift.git'
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'centos:latest'
    type: Docker
  triggers:
    - type: ConfigChange
    - imageChange:
      type: ImageChange